version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Exponer el puerto de MongoDB para acceso desde fuera del contenedor
    volumes:
      - mongodb-data:/data/db

  logservice1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "35001:8080"
    depends_on:
      - mongodb

  logservice2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "35002:8080"
    depends_on:
      - mongodb

  logservice3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "35003:8080"
    depends_on:
      - mongodb

volumes:
  mongodb-data:
